'''
 *  $Id: SConstruct, 2014-08-06 16:39:25 DAMPE $
 *----------------------------------------------------------
 *  This file is automatically generated by dmpNewAlg
 *----------------------------------------------------------
 *  1. create a shared library
 *  2. install it into $DMPSWWORK
 *  then, in your JobOpt* file could use your Alg.
 *----------------------------------------------------------
'''

import os

# install share
#--------------------------------------------------------------------
includeDir="./include"
prefix=os.environ['DMPSWSYS']
for tmp in os.listdir(includeDir):
    if ".h" in tmp:
        Default(Command(prefix+'/include/'+tmp,includeDir+'/'+tmp,Copy("$TARGET","$SOURCE")))

